apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-rolling-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: eks-rolling-app
  template:
    metadata:
      labels:
        app: eks-rolling-app
    spec:
      containers:
      - name: eks-container
        image: 142039336074.dkr.ecr.ap-south-1.amazonaws.com/eks-rolling-app:latest
        ports:
        - containerPort: 5000
